---
name: Hello World
type: roadmap
status: done
description: A simple greeting app that generates personalized hellos using AI.
requires: []
---

The starter app. Type a name, get a personalized greeting generated by AI.

~~~
Single method (generateGreeting) using generateText. Single table (greetings)
storing name + generated text. Minimal web interface: input, button, result display.
~~~
